/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: OneSteven (https://sketchfab.com/Steven007)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/mclaren-f1-faba9dfe3ae54bb997eb7e1c90180a7b
title: McLaren F1
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
	nodes: {
		gum015_glass001_0: THREE.Mesh;
		gum013_glass_border001_0: THREE.Mesh;
		gum011_plastic_black_ncl1_2_0: THREE.Mesh;
		gum010_light_0: THREE.Mesh;
		gum009_blastic_0: THREE.Mesh;
		gum008_mirrors001_0: THREE.Mesh;
		gum006_plastic_black_ncl1_1_0: THREE.Mesh;
		gum005_carbonfib_0: THREE.Mesh;
		gum004_chr_0: THREE.Mesh;
		gum003_flack_0: THREE.Mesh;
		gum002_Material001_0: THREE.Mesh;
		gum001_grills_0: THREE.Mesh;
		gum000_bod_0: THREE.Mesh;
		wheel003_Material003_0: THREE.Mesh;
		wheel003_Material002_0: THREE.Mesh;
		wheel003_rim_0: THREE.Mesh;
		cal003_Material004_0: THREE.Mesh;
		wheel002_Material003_0: THREE.Mesh;
		wheel002_Material002_0: THREE.Mesh;
		wheel002_rim_0: THREE.Mesh;
		cal002_Material004_0: THREE.Mesh;
		cal001_Material004_0: THREE.Mesh;
		wheel001_Material003_0: THREE.Mesh;
		wheel001_Material002_0: THREE.Mesh;
		wheel001_rim_0: THREE.Mesh;
		gum014_glass_0: THREE.Mesh;
		gum012_red_0: THREE.Mesh;
		gum007_grills_0: THREE.Mesh;
		gum016_det_0: THREE.Mesh;
		cal_Material004_0: THREE.Mesh;
		wheel_Material003_0: THREE.Mesh;
		wheel_Material002_0: THREE.Mesh;
		wheel_rim_0: THREE.Mesh;
	};
	materials: {
		["glass.001"]: THREE.MeshStandardMaterial;
		["glass_border.001"]: THREE.MeshStandardMaterial;
		plastic_black_ncl1_2: THREE.MeshStandardMaterial;
		light: THREE.MeshStandardMaterial;
		blastic: THREE.MeshStandardMaterial;
		["mirrors.001"]: THREE.MeshStandardMaterial;
		plastic_black_ncl1_1: THREE.MeshStandardMaterial;
		carbonfib: THREE.MeshStandardMaterial;
		material: THREE.MeshStandardMaterial;
		flack: THREE.MeshStandardMaterial;
		["Material.001"]: THREE.MeshStandardMaterial;
		grills: THREE.MeshStandardMaterial;
		material_12: THREE.MeshStandardMaterial;
		["Material.003"]: THREE.MeshStandardMaterial;
		["Material.002"]: THREE.MeshStandardMaterial;
		material_15: THREE.MeshStandardMaterial;
		["Material.004"]: THREE.MeshStandardMaterial;
		glass: THREE.MeshStandardMaterial;
		material_18: THREE.MeshStandardMaterial;
		material_19: THREE.MeshStandardMaterial;
	};
};

const modelId = "61b80a63a64bccc018f46cfa";
const url = `../models/${modelId}/scene.gltf`;

export default function Model({ ...props }: JSX.IntrinsicElements["group"]) {
	const group = useRef<THREE.Group>();
	const { nodes, materials } = useGLTF(url) as GLTFResult;

	useFrame(() => (group.current!.rotation.y -= 0.005));

	return (
		<group ref={group} {...props} dispose={null}>
			<group
				rotation={[-Math.PI / 2, 0, 0]}
				scale={[0.015, 0.015, 0.015]}
				position={[0, -1, 0]}
			>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<group
						position={[0, 89.64, 14.91]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={[100, 100, 100]}
					>
						<mesh
							geometry={nodes.gum015_glass001_0.geometry}
							material={materials["glass.001"]}
						/>
					</group>
					<group
						position={[0, 57.32, 189.7]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={[100, 100, 100]}
					>
						<mesh
							geometry={nodes.gum013_glass_border001_0.geometry}
							material={materials["glass_border.001"]}
						/>
					</group>
					<group
						position={[0, 64.01, -4.23]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={[100, 100, 100]}
					>
						<mesh
							geometry={nodes.gum011_plastic_black_ncl1_2_0.geometry}
							material={materials.plastic_black_ncl1_2}
						/>
					</group>
					<group
						position={[0, 40.74, 210.92]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={[100, 100, 100]}
					>
						<mesh
							geometry={nodes.gum010_light_0.geometry}
							material={materials.light}
						/>
					</group>
					<group
						position={[0, 63.13, 15.32]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={[100, 100, 100]}
					>
						<mesh
							geometry={nodes.gum009_blastic_0.geometry}
							material={materials.blastic}
						/>
					</group>
					<group
						position={[0, 83.52, 90.49]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={[100, 100, 100]}
					>
						<mesh
							geometry={nodes.gum008_mirrors001_0.geometry}
							material={materials["mirrors.001"]}
						/>
					</group>
					<group
						position={[17.5, 53.87, 168.97]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={[100, 100, 100]}
					>
						<mesh
							geometry={nodes.gum006_plastic_black_ncl1_1_0.geometry}
							material={materials.plastic_black_ncl1_1}
						/>
					</group>
					<group
						position={[0, 21.84, -140.75]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={[100, 100, 100]}
					>
						<mesh
							geometry={nodes.gum005_carbonfib_0.geometry}
							material={materials.carbonfib}
						/>
					</group>
					<group
						position={[0, 36.92, -187.51]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={[100, 100, 100]}
					>
						<mesh
							geometry={nodes.gum004_chr_0.geometry}
							material={materials.material}
						/>
					</group>
					<group
						position={[0, 50.2, 14.03]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={[100, 100, 100]}
					>
						<mesh
							geometry={nodes.gum003_flack_0.geometry}
							material={materials.flack}
						/>
					</group>
					<group
						position={[0, 48.45, 156.72]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={[100, 100, 100]}
					>
						<mesh
							geometry={nodes.gum002_Material001_0.geometry}
							material={materials["Material.001"]}
						/>
					</group>
					<group
						position={[0, 65.32, 7.85]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={[100, 100, 100]}
					>
						<mesh
							geometry={nodes.gum001_grills_0.geometry}
							material={nodes.gum001_grills_0.material}
						/>
					</group>
					<group
						position={[0, 64.52, 18.96]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={[100, 100, 100]}
					>
						<mesh
							geometry={nodes.gum000_bod_0.geometry}
							material={materials.material_12}
						/>
					</group>
					<group
						position={[79.02, 34.24, -136.78]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={[1.02, 1.09, 1.09]}
					>
						<mesh
							geometry={nodes.wheel003_Material003_0.geometry}
							material={nodes.wheel003_Material003_0.material}
						/>
						<mesh
							geometry={nodes.wheel003_Material002_0.geometry}
							material={nodes.wheel003_Material002_0.material}
						/>
						<mesh
							geometry={nodes.wheel003_rim_0.geometry}
							material={nodes.wheel003_rim_0.material}
						/>
					</group>
					<group
						position={[79.02, 34.24, -136.78]}
						rotation={[0.52, 0, 0]}
						scale={[0.91, 0.98, 0.98]}
					>
						<mesh
							geometry={nodes.cal003_Material004_0.geometry}
							material={nodes.cal003_Material004_0.material}
						/>
					</group>
					<group
						position={[-79.02, 34.24, -136.78]}
						rotation={[-Math.PI / 2, 0, -Math.PI]}
						scale={[1.02, 1.09, 1.09]}
					>
						<mesh
							geometry={nodes.wheel002_Material003_0.geometry}
							material={nodes.wheel002_Material003_0.material}
						/>
						<mesh
							geometry={nodes.wheel002_Material002_0.geometry}
							material={nodes.wheel002_Material002_0.material}
						/>
						<mesh
							geometry={nodes.wheel002_rim_0.geometry}
							material={nodes.wheel002_rim_0.material}
						/>
					</group>
					<group
						position={[-79.02, 34.24, -136.78]}
						rotation={[0.52, 0, 0]}
						scale={[-0.91, 0.98, 0.98]}
					>
						<mesh
							geometry={nodes.cal002_Material004_0.geometry}
							material={nodes.cal002_Material004_0.material}
						/>
					</group>
					<group
						position={[-80.7, 29.17, 135.09]}
						rotation={[0.54, -0.27, 0.16]}
						scale={[-0.93, 0.93, 0.93]}
					>
						<mesh
							geometry={nodes.cal001_Material004_0.geometry}
							material={nodes.cal001_Material004_0.material}
						/>
					</group>
					<group
						position={[-80.7, 29.17, 135.09]}
						rotation={[-Math.PI / 2, 0, 2.83]}
						scale={1.04}
					>
						<mesh
							geometry={nodes.wheel001_Material003_0.geometry}
							material={nodes.wheel001_Material003_0.material}
						/>
						<mesh
							geometry={nodes.wheel001_Material002_0.geometry}
							material={nodes.wheel001_Material002_0.material}
						/>
						<mesh
							geometry={nodes.wheel001_rim_0.geometry}
							material={nodes.wheel001_rim_0.material}
						/>
					</group>
					<group
						position={[0, 57.46, 188.32]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={[100, 100, 100]}
					>
						<mesh
							geometry={nodes.gum014_glass_0.geometry}
							material={materials.glass}
						/>
					</group>
					<group
						position={[0, 54.59, -190.41]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={[100, 100, 100]}
					>
						<mesh
							geometry={nodes.gum012_red_0.geometry}
							material={materials.material_18}
						/>
					</group>
					<group
						position={[0, 80.21, -137.04]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={[100, 100, 100]}
					>
						<mesh
							geometry={nodes.gum007_grills_0.geometry}
							material={nodes.gum007_grills_0.material}
						/>
					</group>
					<group
						position={[0, 56.75, 179.45]}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={[100, 100, 100]}
					>
						<mesh
							geometry={nodes.gum016_det_0.geometry}
							material={materials.material_19}
						/>
					</group>
					<group
						position={[80.7, 29.17, 135.09]}
						rotation={[0.54, -0.27, 0.16]}
						scale={[0.93, 0.93, 0.93]}
					>
						<mesh
							geometry={nodes.cal_Material004_0.geometry}
							material={nodes.cal_Material004_0.material}
						/>
					</group>
					<group
						position={[80.7, 29.17, 135.09]}
						rotation={[-Math.PI / 2, 0, -Math.PI / 10]}
						scale={1.04}
					>
						<mesh
							geometry={nodes.wheel_Material003_0.geometry}
							material={nodes.wheel_Material003_0.material}
						/>
						<mesh
							geometry={nodes.wheel_Material002_0.geometry}
							material={nodes.wheel_Material002_0.material}
						/>
						<mesh
							geometry={nodes.wheel_rim_0.geometry}
							material={nodes.wheel_rim_0.material}
						/>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload(url);
